// src/app/layout.tsx
import type { Metadata } from "next";
import { Playfair_Display, Geist_Mono } from "next/font/google";
import "./globals.css";
import InteractiveStarryBg from "@/app/components/stars"; // Adjust path if your component is elsewhere
import Head from 'next/head';


// Configure Playfair Display
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

// Keep Geist_Mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Portfolio with Playfair Display",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          href="https://unpkg.com/@heroicons/react@24/solid"
          as="script"
          crossOrigin="anonymous"
        />
        <Head>
          <link
            rel="preload"
            href="/astronaut.svg"
            as="image"
            type="image/svg+xml"
          />
        </Head>
      </Head>
      <body
        className={`
          ${playfair.variable} 
          ${geistMono.variable} 
          font-sans
          bg-gradient-to-br 
          from-[#0A162E] from-[10%]
          via-[#023A69] via-[37%]
          via-[#02528D] via-[67%]
          via-[#0F2240] via-[84%]
          to-[#014A81] via-[100%]
          bg-fixed
        `}
      >
        <InteractiveStarryBg />
        {/* Wrap children in a main tag or div to control its stacking context if necessary */}
        <main className="relative z-[1]">
          {/* z-[1] (or any z-index > -1) ensures this content is above the canvas (which is z-[-1]).
            'relative' is needed for z-index to take effect on this main element.
          */}
          {children}
        </main>
      </body>
    </html >
  );
}