
import type { Metadata } from "next";
import { Playfair_Display, Geist_Mono } from "next/font/google";
import "./globals.css";
import InteractiveStarryBg from "@/app/components/stars";

// Configure Playfair Display
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

// Keep Geist_Mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Theo's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.svg', // Main favicon
    shortcut: '/logo.svg', // Alternative shortcut icon
    apple: '/logo.svg', // Apple touch icon
    other: {
      rel: 'apple-touch-icon-precomposed',
      url: '/apple-touch-icon-precomposed.png',
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preload important resources */}
        <link
          rel="preload"
          href="https://unpkg.com/@heroicons/react@24/solid"
          as="script"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/astronaut.svg"
          as="image"
          type="image/svg+xml"
        />
      </head>
      <body
        className={`
          ${playfair.variable} 
          ${geistMono.variable} 
          font-sans
          bg-gradient-to-tl 
          from-[#0F2240] from-[0%]
          via-[#023A69] via-[50%]
          to-[#0A162E] to-[100%]
          bg-fixed
        `}
      >
        <InteractiveStarryBg />
        <main className="relative z-[1]">
          {children}
        </main>
      </body>
    </html>
  );
}